language: python
python:
- '2.7'
- '3.4'
before_install:
- if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh
  -O miniconda.sh; else wget http://repo.continuum.io/miniconda/Miniconda3-3.4.2-Linux-x86_64.sh
  -O miniconda.sh; fi
- chmod +x miniconda.sh
- "./miniconda.sh -b"
- if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then export PATH=~/miniconda2/bin:$PATH;
  else export PATH=~/miniconda3/bin/:$PATH; fi
- conda update --yes conda
install:
- conda create -n testenv --yes python=$TRAVIS_PYTHON_VERSION pip
- source activate testenv
- conda install --yes --channel bioconda --file conda_requirements.txt
- pip install -r requirements.txt
- pip install .
before_script:
- git config --global user.email "olga.botvinnik@gmail.com"
- git config --global user.name "olgabot"
- git config --global push.default simple
- export REPO_URL_GITHUB="https://$GH_TOKEN@github.com/$GH_REPO.git"
script:
- make coverage
- make lint
after_script:
- pip install coverage
- coveralls
deploy:
  provider: pypi
  on:
    tags: true
    repo: olgabot/kvector
env:
  global:
    secure: Cevobc4aRT8TBvvAQTlro1D6pgrRntWjBi08sk3Ok40LH4W0gWoiGW4l4CMppvW7yVc4TZYYCQfIs0rgqhg+UWO3uCgqtSjE5irbPIWyu8OLPlDssLxLcNDGigLONGVaIcbAVlEeAcidWfE/0LEiZNev5GoIt25fVB+Ds/2/VZTYTjRSU6Txypm2Vuy0Xi/mueXHLnWvah65C0/q1OHjjV/Fl1yd/M3u7xS9mj3kMcAhBHCzEQlx/RECqzfBZjQ4Ac7sqfwPej2+2sIj5OCNQLgSQXCXaTUiylkqJ2ixQSB1lRzs1DBCrv8xo2vfVGgQFrhhitv1BdiP6KYXyZcJdfStmAniU5soEGPD+KiG8Zb7tjY39lP+N+RONJSpw0f0YBXiDftZ9PNV8WT1l/d8P8hjAzqdIUmBpruOsF67xXs/HGGLuUzKzGKazXcwUSOxG5YV7JR+rHTRm0iyLmBLmD8tcZPDG2Mm32+iuDoCLaav5gWdK86zS1R+9dPbWQ+KZ1OKYu+oxMnVSggAcTwNvfIGmwkH87FhHwk39ZSUfBpoeVgURd1yhmqCKXuP9sPZlZpZoBzlAMLdgoe+/kUXgomStZHrrHf1GNZBDfm5zdiXnBQSb9h8sS9TuyElyW93lQ20q4gEKbdpb9BXlpPmvIn7PBUQDHHxY9iENuUns44=
